name: Lighthouse Report

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.html'

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install -g http-server @lhci/cli

      - name: Start local server
        run: |
          http-server . -p 8080 -c-1 &
          sleep 5

      - name: Run Lighthouse CI
        run: |
          lhci autorun --collect.url=http://localhost:8080 --upload.target=filesystem --upload.outputDir=./lhci-report || true

      - name: Show Lighthouse scores in console
        run: |
          REPORT=$(find lhci-report -name 'manifest.json' | head -n 1)
          if [ -f "$REPORT" ]; then
            echo "📊 Lighthouse scores:"
            cat "$REPORT" | jq -r '.summary[] | "\(.label): \(.value)"'
          else
            echo "⚠️ No Lighthouse report found."
          fi

      - name: Upload Lighthouse report artifact
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: lhci-report
