name: Lighthouse Accessibility Report

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install -g http-server @lhci/cli

      - name: Start local server
        run: |
          http-server -p 8080 -c-1 &
          sleep 5

      - name: Run Lighthouse CI
        run: |
          lhci collect --url=http://localhost:8080/index.html --outputPath=./lighthouse-report || true

      - name: Upload Lighthouse Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: lighthouse-report/
