name: Lighthouse Audit

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lighthouse-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install http-server @lhci/cli

      - name: Start HTTP server
        run: |
          npx http-server -p 8080 -c-1 &
          sleep 5  # tiempo para levantar el servidor

      - name: Run Lighthouse CI
        run: |
          npx lhci autorun --collect.url=http://localhost:8080/index.html --upload.target=filesystem --upload.outputDir=./lhci-report

      - name: Upload Lighthouse report artifact
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ./lhci-report

