name: HTML Validation

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.html'

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Validación de HTML con htmlhint
      - name: Install htmlhint locally
        run: |
          npm install htmlhint

      - name: Validate HTML files with htmlhint
        run: |
          npx htmlhint '**/*.html' || exit 1

      - name: Download vnu-jar
        run: |
          wget https://github.com/validator/validator/releases/download/latest/vnu.jar
      - name: Validate HTML with vnu
        run: |
          java -jar vnu.jar --errors-only --exit-zero-always ./

