name: HTML & Accesibility Validation

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.html'

jobs:
  validate-html-accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install htmlhint axe-cli http-server

      - name: Validate HTML files with HTMLHint
        run: |
          npx htmlhint **/*.html || exit 1

      - name: Start local server
        run: |
          npx http-server -p 8080 -c-1 &  # Levanta servidor local
          sleep 3  # Asegurarse de que el servidor esté corriendo

      - name: Validate Accessibility with axe-cli
        run: |
          npx axe http://localhost:8080/index.html --output=json --runOnly wcag2a
