name: HTML & Accessibility Validation

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.html'

jobs:
  validate-html-accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Validación de HTML con htmlhint sin instalar globalmente
      - name: Install htmlhint locally
        run: |
          npm install htmlhint

      - name: Validate HTML files with htmlhint
        run: |
          npx htmlhint **/*.html || exit 1

      # Levantar un servidor local
      - name: Install and run HTTP server
        run: |
          npm install http-server
          npx http-server -p 8080 -c-1 &

      # Validación de accesibilidad con axe-cli
      - name: Install axe-cli
        run: |
          npm install axe-cli

      - name: Run accessibility tests with axe-cli
        run: |
          npx axe http://localhost:8080/index.html --output=json --runOnly wcag2a
