name: HTML & Accesibility Validation

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.html'

jobs:
  validate-html-accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies locally
        run: |
          npm install htmlhint pa11y http-server

      - name: Validate HTML files with HTMLHint
        run: |
          npx htmlhint **/*.html || exit 1

      - name: Validate Accessibility with Pa11y
        run: |
          npx http-server -p 8080 -c-1 &  # Levanta servidor local
          sleep 3
          npx pa11y http://localhost:8080/index.html --standard WCAG2AA --reporter cli --no-sandbox
