name: HTML & Accessibility Validation

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.html'

jobs:
  validate-html-accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Instalar htmlhint localmente
      - name: Install htmlhint locally
        run: |
          npm install htmlhint

      # Obtener lista de archivos .html modificados
      - name: Get changed HTML files
        id: changed_html
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} | grep '.html$' || true)
          echo "files=$CHANGED_FILES" >> $GITHUB_OUTPUT

      # Validación con htmlhint si hay archivos modificados
      - name: Run htmlhint if HTML files changed
        if: steps.changed_html.outputs.files != ''
        run: |
          npx htmlhint ${{ steps.changed_html.outputs.files }}

      # Validación con vnu.jar si hay archivos modificados
      - name: Run vnu.jar validator if HTML files changed
        if: steps.changed_html.outputs.files != ''
        run: |
          java -jar .github/tools/vnu.jar --errors-only ${{ steps.changed_html.outputs.files }}
