name: HTML & Accesibility Validation

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.html'

jobs:
  validate-html-accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install eslint eslint-plugin-jsx-a11y

      - name: Lint HTML files for accessibility issues
        run: |
          npx eslint **/*.html --ext .html --rule 'jsx-a11y/*: error'
