name: HTML & Accessibility Validation

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**/*.html'

jobs:
  validate-html-accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install HTMLHint, Pa11y and http-server
        run: |
          npm install -g htmlhint pa11y http-server

      - name: Validate HTML files with HTMLHint
        run: |
          htmlhint **/*.html || exit 1

      - name: Validate Accessibility with Pa11y
        run: |
          http-server -p 8080 -c-1 &
          sleep 3
          pa11y http://localhost:8080/index.html --standard WCAG2AA --reporter cli

